apiVersion: v1
kind: Service
metadata:
  name: mern-app-service
  labels:
    app: mern-app
spec:
  type: NodePort
  selector:
    app: mern-app
  ports:
    - name: frontend-port
      protocol: TCP
      nodePort: 30300
      port: 3000
      targetPort: 3000
    - name: backend-port
      protocol: TCP
      port: 5000
      targetPort: 5000
