name: Workflow

on:
  workflow_dispatch:

jobs:
  Provision-Networking:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Provision EKS Cluster
      run: |
        aws cloudformation deploy \
          --template-file eks-vpc-stack.yaml \
          --stack-name my-eks-vpc \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Wait for stack creation
      run: |
        aws cloudformation wait stack-create-complete \
          --region ap-south-1 \
          --stack-name my-eks-vpc

  Provision-EKS:
      runs-on: ubuntu-latest
      needs: [Provision-Networking]
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
  
      - name: Provision EKS Cluster
        run: |
          aws cloudformation create-stack \
            --region ap-south-1 \
            --stack-name my-eks-cluster \
            --capabilities CAPABILITY_NAMED_IAM \
            --template-body file://eks-stack.yaml

      - name: Wait for stack creation
        run: |
          aws cloudformation wait stack-create-complete \
            --region ap-south-1 \
            --stack-name my-eks-cluster

  Configure-Kubectl-and-Apply-Deployment:
    runs-on: ubuntu-latest
    needs: [Provision-EKS]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Configure kubeconfig
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name my-eks-cluster

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f backend-deployment.yaml
          kubectl apply -f service.yaml
